version: '3'
services:

  mongodb:
    image: mongo:3.6.5-jessie
    container_name: mongodb

  toolkit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Toolkit
    environment:
      - MONGODB_HOSTNAME=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USERNAME=
      - MONGODB_PASSWORD=
    depends_on:
      - mongodb
    ports:
      - 5005:5005

  
  
